### PR TITLE
Removed VirtualBox instructions

### PR DESCRIPTION
**Pull request by jakrmpotic**
OVA files are not available at this time.

### CODE REVIEW

**Comment by chanskw** [comment]
Hi Jasna, is this ready to be pulled in?  Any more changes?

**Comment by jakrmpotic** [comment]
I'd like Nancy to review the steps first. Stay tuned!

**Comment by chanskw** [comment]
Ok, please indicate when it's ready and I will pull it in.  Thank you!

**Review by nlweir — APPROVED** [review]
I approve these changes. Thank you Jasna.

**Comment by jakrmpotic** [comment]
@nlweir Thanks !
@chanskw  - pls pull in the changes :-)

**Comment by chanskw** [comment]
The same documentation is also in doc/latest directory.  This is not ideal that the doc is duplicated.  But the "latest" link is maintained for external sites to point to this site, without having to worry about which release is the latest release.  We will look at creating link forwarding.  But for now, we need to make the changes in the latest directory as well.  I have copied the file over.

**Pull request merged**
