### PR TITLE
Update format to readthedocs

### PR DESCRIPTION
**Pull request by wmarshall484**

### CODE REVIEW

**Comment by chanskw** [comment]
@wmarshall484 do you have instructions on how to test this out locally?  I need to understand how files are moved around and whether we have preserved existing links.

**Comment by wmarshall484** [comment]
Hi @chanskw,

Yes, I updated the links when I made the change.

To try it out locally, install 'mkdocs' on your machine, [you can find instructions here](http://www.mkdocs.org/#installation).

Then, clone my branch (git@github.com:wmarshall484/streamsx.documentation.git).

In the top-level directory, type 'mkdocs serve'. It should start up a webserver and you should be able to see the new layout.

**Comment by wmarshall484** [comment]
@chanskw, did you have any luck?

**Comment by wmarshall484** [comment]
I'd like to continue the discussion on changing the format to ReadTheDocs. In the time that this PR has been up, a number of merge conflicts have arisen. Before anyone starts resolving them, are there concerns about moving to this theme?

Theme: http://wmarshall484.github.io/streamsx.documentation/

**Pull request closed without merging**
